--- REVERSE
DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H = 198;
DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H = 200;
DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H = 203;
DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H = 204;
DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H = 205;
