
-- Actividades de establecimientos industriales-Alimento /609/198
BEGIN
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 1, 'Fabricación de extractos alimenticios de granos', 'Fabricación de extractos alimenticios de granos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 2, 'Preparación y venta de pizzas, hamburguesas, etc.', 'Preparación y venta de pizzas, hamburguesas, etc.', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 3, 'Matanza de ganado y aves', 'Matanza de ganado y aves', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 4, 'Corte y empacado de carnes', 'Corte y empacado de carnes', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 5, 'Fabricación de embutidos y conservas de carnes', 'Fabricación de embutidos y conservas de carnes', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 6, 'Fabricación de crema, queso y mantequilla', 'Fabricación de crema, queso y mantequilla', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 7, 'Pasteurización, deshidratación, evaporación y condensación de leche', 'Pasteurización, deshidratación, evaporación y condensación de leche', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 8, 'Fabricación de helados y paletas', 'Fabricación de helados y paletas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 9, 'Fabricación de cajetas y otros dulces de leche', 'Fabricación de cajetas y otros dulces de leche', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 10, 'Deshidratación, molienda y envasado de productos agrícolas', 'Deshidratación, molienda y envasado de productos agrícolas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 11, 'Fabricación de sopas y guisos preparados', 'Fabricación de sopas y guisos preparados', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 12, 'Congelación de productos alimenticios', 'Congelación de productos alimenticios', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 13, 'Preparación y envasado de alimentos', 'Preparación y envasado de alimentos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 14, 'Secado, salado de harinas de pescados y mariscos', 'Secado, salado de harinas de pescados y mariscos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 15, 'Fabricación de concentrados para caldos', 'Fabricación de concentrados para caldos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 16, 'Beneficio de arroz', 'Beneficio de arroz', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 17, 'Beneficio de café', 'Beneficio de café', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 18, 'Tostado y molienda de café', 'Tostado y molienda de café', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 19, 'Fabricación de harinas', 'Fabricación de harinas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 20, 'Beneficio y molienda de otros productos agrícolas', 'Beneficio y molienda de otros productos agrícolas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 21, 'Fabricación de galletas y pastas', 'Fabricación de galletas y pastas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 22, 'Panaderías', 'Panaderías', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 23, 'Fabricación de masa y/o tortilla', 'Fabricación de masa y/o tortilla', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 24, 'Envasado y compactación de azúcar', 'Envasado y compactación de azúcar', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 25, 'Ingenios azucareros', 'Ingenios azucareros', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 26, 'Fabricación de piloncillo', 'Fabricación de piloncillo', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 27, 'Fabricación de chocolates y confitería de cacao', 'Fabricación de chocolates y confitería de cacao', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 28, 'Fabricación de dulces y caramelos', 'Fabricación de dulces y caramelos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 29, 'Fabricación de chicles', 'Fabricación de chicles', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 30, 'Fabricación de café soluble y productos relacionados', 'Fabricación de café soluble y productos relacionados', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 31, 'Fabricación de concentrados para preparar bebidas', 'Fabricación de concentrados para preparar bebidas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 32, 'Tratamiento y envasado de miel de abeja', 'Tratamiento y envasado de miel de abeja', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 33, 'Fabricación de hielo y sus productos', 'Fabricación de hielo y sus productos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 34, 'Fabricación de hielo y sus productos', 'Fabricación de hielo y sus productos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 35, 'Fabricación de postres en polvo', 'Fabricación de postres en polvo', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 36, 'Fabricación de botanas, frituras y similares', 'Fabricación de botanas, frituras y similares', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 37, 'Procesamiento de té', 'Procesamiento de té', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 38, 'Fabricación de alimentos para animales', 'Fabricación de alimentos para animales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 39, 'Fabricación de aditivos para alimentos', 'Fabricación de aditivos para alimentos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 40, 'Incubación, cría y engorda de animales para consumo alimenticio', 'Incubación, cría y engorda de animales para consumo alimenticio', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 41, 'Fabricación de productos lácteos', 'Fabricación de productos lácteos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 42, 'Fabricación de cereales', 'Fabricación de cereales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 43, 'Envasado de aguas purificadas o de manantial', 'Envasado de aguas purificadas o de manantial', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 44, 'Almacenes de productos congelados y en refrigeración', 'Almacenes de productos congelados y en refrigeración', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 45, 'Fabricación de sebo y harina de hueso y carne', 'Fabricación de sebo y harina de hueso y carne', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 46, 'Invernaderos', 'Invernaderos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (198, null, 47, 'Otros', 'Otros', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
  	COMMIT;
END;



-- Actividades de establecimientos industriales-Textil /616 /200
BEGIN
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 1, ' Estampado y/o acabado de ropa y productos de otros materiales', 'Estampado y/o acabado de ropa y productos de otros materiales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 2, 'Fabricación de productos y artículos de fibras naturales', 'Fabricación de productos y artículos de fibras naturales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 3, 'Despepite y empacado de algodón', 'Despepite y empacado de algodón', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 4, 'Fabricación de hilos para coser, bordar y tejer', 'Fabricación de hilos para coser, bordar y tejer', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 5, 'Fabricación de estambres', 'Fabricación de estambres', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 6, 'Fabricación de telas y sus productos', 'Fabricación de telas y sus productos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 7, 'Acabado de fibras, hilos, hilados y telas textiles', 'Acabado de fibras, hilos, hilados y telas textiles', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 8, 'Fabricación de fieltros y entretelas', 'Fabricación de fieltros y entretelas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 9, 'Tejido de rafia sintética', 'Tejido de rafia sintética', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 10, 'Fabricación de redes y mallas textiles', 'Fabricación de redes y mallas textiles', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 11, 'Fabricación de artículos textiles con materiales reciclados', 'Fabricación de artículos textiles con materiales reciclados', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 12, 'Fabricación de artículos de algodón', 'Fabricación de artículos de algodón', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 13, 'Confección de toldos y cubiertas textiles de uso automotriz', 'Confección de toldos y cubiertas textiles de uso automotriz', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 14, 'Fabricación de bolsas y costales textiles', 'Fabricación de bolsas y costales textiles', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 15, 'Tejido a máquina de alfombras y tapetes', 'Tejido a máquina de alfombras y tapetes', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 16, 'Tejido de prendas de vestir', 'Tejido de prendas de vestir', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 17, 'Confección de prendas de vestir', 'Confección de prendas de vestir', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 18, 'Confección de ropa de cuero o piel', 'Confección de ropa de cuero o piel', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 19, 'Fabricación de sombreros y similares', 'Fabricación de sombreros y similares', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 20, 'Fabricación de accesorios para vestir', 'Fabricación de accesorios para vestir', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 21, 'Curtido y acabado de cuero/piel y sus productos', 'Curtido y acabado de cuero/piel y sus productos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 22, 'Fabricación de calzado', 'Fabricación de calzado', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 23, 'Fabricación de pavilos y mechas de algodón para velas y veladoras', 'Fabricación de pavilos y mechas de algodón para velas y veladoras', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 24, 'Fabricación de fibras y cordeles', 'Fabricación de fibras y cordeles', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 25, 'Fabricación de otros artículos textiles recubiertos', 'Fabricación de otros artículos textiles recubiertos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 26, 'Fabricación de pañales y artículos sanitarios', 'Fabricación de pañales y artículos sanitarios', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (200, null, 27, 'Otros', 'Otros', 0, 'F101', 'CURRENT_TIMESTAMP', 'F101', 'CURRENT_TIMESTAMP', null);
  	COMMIT;
END;


-- Actividades de establecimientos industriales-Metal/614/203
BEGIN
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 1, 'Fabricación de elevadores y/o escaleras eléctricas', 'Fabricación de elevadores y/o escaleras eléctricas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 2, 'Fabricación de artículos ornamentales', 'Fabricación de artículos ornamentales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 3, 'Fabricación de cilindros, tanques y otros contenedores metálicos', 'Fabricación de cilindros, tanques y otros contenedores metálicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 4, 'Fabricación de calderas industriales e intercambiadores de calor', 'Fabricación de calderas industriales e intercambiadores de calor', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 5, 'Fabricación de artículos y productos metálicos', 'Fabricación de artículos y productos metálicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 6, 'Fabricación de cerraduras, candados y llaves', 'Fabricación de cerraduras, candados y llaves', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 7, 'Fabricación de alambre y sus productos', 'Fabricación de alambre y sus productos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 8, 'Fabricación de tornillos, clavos, tuercas, etc.', 'Fabricación de tornillos, clavos, tuercas, etc.', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 9, 'Fabricación de envases metálicos', 'Fabricación de envases metálicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 10, 'Fabricación de artículos maquinados', 'Fabricación de artículos maquinados', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 11, 'Fabricación de válvulas metálicas', 'Fabricación de válvulas metálicas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 12, 'Fabricación de calentadores y quemadores', 'Fabricación de calentadores y quemadores', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 13, 'Fabricación de baterías de cocina', 'Fabricación de baterías de cocina', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 14, 'Fabricación de maquinaria, equipos, aparatos, partes y/o sus piezas', 'Fabricación de maquinaria, equipos, aparatos, partes y/o sus piezas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 15, 'Fabricación de aparatos de refrigeración y/o aire acondicionado', 'Fabricación de aparatos de refrigeración y/o aire acondicionado', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 16, 'Fabricación de filtros', 'Fabricación de filtros', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 17, 'Fabricación de partes y equipos para transportes mecánicos', 'Fabricación de partes y equipos para transportes mecánicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 18, 'Fabricación de joyería y orfebrería', 'Fabricación de joyería y orfebrería', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 19, 'Fabricación de motores en general', 'Fabricación de motores en general', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (203, null, 20, 'Otros', 'Otros', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
  	COMMIT;
END;


-- Actividades de establecimientos industriales-Electronica /612/204
BEGIN
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 1, 'Fabricación de máquinas de oficina', 'Fabricación de máquinas de oficina', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 2, 'Fabricación de equipos de cómputo y sus periférico', 'Fabricación de equipos de cómputo y sus periférico', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 3, 'Fabricación de motores eléctricos', 'Fabricación de motores eléctricos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 4, 'Fabricación de electrodos', 'Fabricación de electrodos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 5, 'Fabricación de aparatos, equipos y/o accesorios eléctricos y/o electrónicos', 'Fabricación de aparatos, equipos y/o accesorios eléctricos y/o electrónicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 6, 'Fabricación de focos y tubos de iluminación', 'Fabricación de focos y tubos de iluminación', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 7, 'Fabricación de anuncios', 'Fabricación de anuncios', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 8, 'Fabricación de estufas y hornos domésticos', 'Fabricación de estufas y hornos domésticos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 9, 'Fabricación de lavadoras de ropa de uso doméstico', 'Fabricación de lavadoras de ropa de uso doméstico', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (204, null, 10, 'Otros', 'Otros', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
  	COMMIT;
END;


-- Actividades de establecimientos industriales-CompDifMat/611/205
BEGIN
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 1, 'Fabricación de equipos y/o artículos, médicos y/o quirúrgicos', 'Fabricación de equipos y/o artículos, médicos y/o quirúrgicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 2, 'Artículos y productos compuestos de diferentes materiales', 'Artículos y productos compuestos de diferentes materiales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 3, 'Fabricación de colchones y box springs', 'Fabricación de colchones y box springs', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 4, 'Fabricación de persianas', 'Fabricación de persianas', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 5, 'Fabricación de relojes', 'Fabricación de relojes', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 6, 'Fabricación de instrumentos musicales', 'Fabricación de instrumentos musicales', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 7, 'Fabricación de artículos y aparatos deportivos', 'Fabricación de artículos y aparatos deportivos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 8, 'Fabricación de artículos escolares', 'Fabricación de artículos escolares', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 9, 'Fabricación de juguetes', 'Fabricación de juguetes', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 10, 'Fabricación de escobas, cepillos y similares', 'Fabricación de escobas, cepillos y similares', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 11, 'Fabricación de sellos metálicos y de goma', 'Fabricación de sellos metálicos y de goma', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 12, 'Fabricación de cierres de cremallera', 'Fabricación de cierres de cremallera', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 13, 'Fabricación de extintores para combatir fuegos', 'Fabricación de extintores para combatir fuegos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 14, 'Fabricación de equipos, materiales e instrumentos ortopédicos', 'Fabricación de equipos, materiales e instrumentos ortopédicos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 15, 'Fabricación de productos electrodomésticos', 'Fabricación de productos electrodomésticos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 16, 'Fabricación de cintas y otros adhesivos', 'Fabricación de cintas y otros adhesivos', 0, 'F101', CURRENT_TIMESTAMP, 'F101', CURRENT_TIMESTAMP, null);
	INSERT INTO MGR_SIGEM.CATALOG(ID_CATALOG_H, CORDER, CODE, NAME, DESCRIPTION, FDL, CBU, CAT, LUU, UAT, CUSTOM_ATTRIBUTES) VALUES (205, null, 17, 'Otros', 'Otros', 0, 'F101', 'CURRENT_TIMESTAMP', 'F101', 'CURRENT_TIMESTAMP', null);
  	COMMIT;
END;


