
BEGIN
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =129
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =153
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =151
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =120
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =121
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =128
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =134
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =155
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =157
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =147
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =141
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =149
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =102
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =133
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =137
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =143
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =125
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =107
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =114
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =101
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =130
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =131
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =136
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =165
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =109
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =115
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =124
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =142
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =145
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =146
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =158
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =106
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =122
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =159
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =160
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =166
	DELETE FROM MGR_SIGEM.CATALOG WHERE ID_CATALOG_H =150
  	COMMIT;
END;